<<<<<<< HEAD
theme: jekyll-theme-cayman
defaults:
    - scope:
        path: "assets/pdf"
      values:
        pdf: true
    - scope:
        path: "assets/reports"
      values:
        report: true
    - scope:
        path: "assets/dialogue_papers"
      values:
        dia: true
=======
theme: jekyll-theme-cayman
>>>>>>> 4ba29bd296130cac7ba54dcda6dc186209885fe6
