theme: jekyll-theme-cayman
defaults:
    - scope:
        path: "assets/pdf"
      values:
        pdf: true
    - scope:
        path: "assets/reports"
      values:
        report: true
    - scope:
        path: "assets/dialogue_papers"
      values:
        dia: true
google_analytics: G-0CJ2ZJYZGH

